runtime: python39
entrypoint: gunicorn -b :$PORT --access-logfile - --error-logfile - -k uvicorn.workers.UvicornH11Worker -c gunicorn_config.py main:app
instance_class: F1
default_expiration: "10s"
#default_expiration: "4d 5h"

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
# Luncho API
- url: /v1/.*
  secure: always
  script: auto

# OpenAPI related pages served by FastAPI
- url: /redoc
  secure: always
  script: auto
- url: /doc
  secure: always
  script: auto
- url: /openapi.json
  secure: always
  script: auto

# static files
- url: /img
  static_dir: img

# index.html and bundle files for web site (the Luncho app)
- url: /index.html
  secure: always
  static_files: app-dist/index.html
  upload: app-dist/index.html
- url: /
  secure: always
  static_files: app-dist/index.html
  upload: app-dist/index.html

- url: /(.*\.(js|map|gif|png|jpg|ico|css))$
  secure: always
  static_files: app-dist/\1
  upload: app-dist/(.*\.(js|map|gif|png|jpg|ico|css))$

# All other routes to the bundle for pushState
- url: .*
  secure: always
  static_files: app-dist/index.html
  upload: app-dist/index.html
